// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/counter.dart';
import 'data/models/project.dart';
import 'data/models/row_memo.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3632591137761859193),
    name: 'Counter',
    lastPropertyId: const obx_int.IdUid(10, 8928185829964655637),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3843947805124358332),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8467932943443224579),
        name: 'typeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9119971216465766496),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3538912508785734446),
        name: 'value',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4220632627261938184),
        name: 'targetValue',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6409311255122076137),
        name: 'resetAt',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8865628590794396191),
        name: 'autoResetEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1242216881074291197),
        name: 'secondaryTypeIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 684398579768846715),
        name: 'orderIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8928185829964655637),
        name: 'isLinked',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 56912154864965339),
    name: 'Project',
    lastPropertyId: const obx_int.IdUid(14, 5949652666699062062),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3421344968959532459),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5829215009481612731),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5780905897124313539),
        name: 'statusIndex',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 6960958803239875508),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5495095001332320242),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1304204245350020806),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2440378411404313604),
        name: 'rowCounterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 9052168395293233465),
        relationField: 'rowCounter',
        relationTarget: 'Counter',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5356494094493269155),
        name: 'stitchCounterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 8487913203956185323),
        relationField: 'stitchCounter',
        relationTarget: 'Counter',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2873116436902126093),
        name: 'patternCounterId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 5656448226333148380),
        relationField: 'patternCounter',
        relationTarget: 'Counter',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1699624302455779529),
        name: 'counterHistoryJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8133976123594356589),
        name: 'startDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4884216570791037245),
        name: 'completedDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1889655614927940284),
        name: 'totalWorkSeconds',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5949652666699062062),
        name: 'timerStartedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 3282312659816922589),
        name: 'memos',
        targetId: const obx_int.IdUid(3, 1189483727074397873),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 5758338300307667726),
        name: 'secondaryCounters',
        targetId: const obx_int.IdUid(1, 3632591137761859193),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1189483727074397873),
    name: 'RowMemo',
    lastPropertyId: const obx_int.IdUid(4, 5138494895117851400),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 582216784625109091),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6656833361144199392),
        name: 'rowNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6057109510414876280),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5138494895117851400),
        name: 'notified',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1189483727074397873),
    lastIndexId: const obx_int.IdUid(4, 6960958803239875508),
    lastRelationId: const obx_int.IdUid(2, 5758338300307667726),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [4468402353214468101],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Counter: obx_int.EntityDefinition<Counter>(
      model: _entities[0],
      toOneRelations: (Counter object) => [],
      toManyRelations: (Counter object) => {},
      getId: (Counter object) => object.id,
      setId: (Counter object, int id) {
        object.id = id;
      },
      objectToFB: (Counter object, fb.Builder fbb) {
        final labelOffset = fbb.writeString(object.label);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.typeIndex);
        fbb.addOffset(2, labelOffset);
        fbb.addInt64(3, object.value);
        fbb.addInt64(4, object.targetValue);
        fbb.addInt64(5, object.resetAt);
        fbb.addBool(6, object.autoResetEnabled);
        fbb.addInt64(7, object.secondaryTypeIndex);
        fbb.addInt64(8, object.orderIndex);
        fbb.addBool(9, object.isLinked);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final valueParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final targetValueParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final resetAtParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final autoResetEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final secondaryTypeIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final orderIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final isLinkedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = Counter(
          id: idParam,
          typeIndex: typeIndexParam,
          label: labelParam,
          value: valueParam,
          targetValue: targetValueParam,
          resetAt: resetAtParam,
          autoResetEnabled: autoResetEnabledParam,
          secondaryTypeIndex: secondaryTypeIndexParam,
          orderIndex: orderIndexParam,
          isLinked: isLinkedParam,
        );

        return object;
      },
    ),
    Project: obx_int.EntityDefinition<Project>(
      model: _entities[1],
      toOneRelations: (Project object) => [
        object.rowCounter,
        object.stitchCounter,
        object.patternCounter,
      ],
      toManyRelations: (Project object) => {
        obx_int.RelInfo<Project>.toMany(1, object.id): object.memos,
        obx_int.RelInfo<Project>.toMany(2, object.id): object.secondaryCounters,
      },
      getId: (Project object) => object.id,
      setId: (Project object, int id) {
        object.id = id;
      },
      objectToFB: (Project object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final counterHistoryJsonOffset = fbb.writeString(
          object.counterHistoryJson,
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.statusIndex);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.rowCounter.targetId);
        fbb.addInt64(7, object.stitchCounter.targetId);
        fbb.addInt64(8, object.patternCounter.targetId);
        fbb.addOffset(9, counterHistoryJsonOffset);
        fbb.addInt64(10, object.startDate?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.completedDate?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.totalWorkSeconds);
        fbb.addInt64(13, object.timerStartedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final startDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final completedDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final timerStartedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final statusIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final startDateParam = startDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(startDateValue);
        final completedDateParam = completedDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(completedDateValue);
        final totalWorkSecondsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final timerStartedAtParam = timerStartedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(timerStartedAtValue);
        final counterHistoryJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = Project(
          id: idParam,
          name: nameParam,
          statusIndex: statusIndexParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          startDate: startDateParam,
          completedDate: completedDateParam,
          totalWorkSeconds: totalWorkSecondsParam,
          timerStartedAt: timerStartedAtParam,
          counterHistoryJson: counterHistoryJsonParam,
        );
        object.rowCounter.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.rowCounter.attach(store);
        object.stitchCounter.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.stitchCounter.attach(store);
        object.patternCounter.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        object.patternCounter.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.memos,
          store,
          obx_int.RelInfo<Project>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Project>(
          object.secondaryCounters,
          store,
          obx_int.RelInfo<Project>.toMany(2, object.id),
        );
        return object;
      },
    ),
    RowMemo: obx_int.EntityDefinition<RowMemo>(
      model: _entities[2],
      toOneRelations: (RowMemo object) => [],
      toManyRelations: (RowMemo object) => {},
      getId: (RowMemo object) => object.id,
      setId: (RowMemo object, int id) {
        object.id = id;
      },
      objectToFB: (RowMemo object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.rowNumber);
        fbb.addOffset(2, contentOffset);
        fbb.addBool(3, object.notified);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final rowNumberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final notifiedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          10,
          false,
        );
        final object = RowMemo(
          id: idParam,
          rowNumber: rowNumberParam,
          content: contentParam,
          notified: notifiedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Counter] entity fields to define ObjectBox queries.
class Counter_ {
  /// See [Counter.id].
  static final id = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[0],
  );

  /// See [Counter.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[1],
  );

  /// See [Counter.label].
  static final label = obx.QueryStringProperty<Counter>(
    _entities[0].properties[2],
  );

  /// See [Counter.value].
  static final value = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[3],
  );

  /// See [Counter.targetValue].
  static final targetValue = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[4],
  );

  /// See [Counter.resetAt].
  static final resetAt = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[5],
  );

  /// See [Counter.autoResetEnabled].
  static final autoResetEnabled = obx.QueryBooleanProperty<Counter>(
    _entities[0].properties[6],
  );

  /// See [Counter.secondaryTypeIndex].
  static final secondaryTypeIndex = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[7],
  );

  /// See [Counter.orderIndex].
  static final orderIndex = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[8],
  );

  /// See [Counter.isLinked].
  static final isLinked = obx.QueryBooleanProperty<Counter>(
    _entities[0].properties[9],
  );
}

/// [Project] entity fields to define ObjectBox queries.
class Project_ {
  /// See [Project.id].
  static final id = obx.QueryIntegerProperty<Project>(
    _entities[1].properties[0],
  );

  /// See [Project.name].
  static final name = obx.QueryStringProperty<Project>(
    _entities[1].properties[1],
  );

  /// See [Project.statusIndex].
  static final statusIndex = obx.QueryIntegerProperty<Project>(
    _entities[1].properties[2],
  );

  /// See [Project.createdAt].
  static final createdAt = obx.QueryDateProperty<Project>(
    _entities[1].properties[3],
  );

  /// See [Project.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Project>(
    _entities[1].properties[4],
  );

  /// See [Project.rowCounter].
  static final rowCounter = obx.QueryRelationToOne<Project, Counter>(
    _entities[1].properties[5],
  );

  /// See [Project.stitchCounter].
  static final stitchCounter = obx.QueryRelationToOne<Project, Counter>(
    _entities[1].properties[6],
  );

  /// See [Project.patternCounter].
  static final patternCounter = obx.QueryRelationToOne<Project, Counter>(
    _entities[1].properties[7],
  );

  /// See [Project.counterHistoryJson].
  static final counterHistoryJson = obx.QueryStringProperty<Project>(
    _entities[1].properties[8],
  );

  /// See [Project.startDate].
  static final startDate = obx.QueryDateProperty<Project>(
    _entities[1].properties[9],
  );

  /// See [Project.completedDate].
  static final completedDate = obx.QueryDateProperty<Project>(
    _entities[1].properties[10],
  );

  /// See [Project.totalWorkSeconds].
  static final totalWorkSeconds = obx.QueryIntegerProperty<Project>(
    _entities[1].properties[11],
  );

  /// See [Project.timerStartedAt].
  static final timerStartedAt = obx.QueryDateProperty<Project>(
    _entities[1].properties[12],
  );

  /// see [Project.memos]
  static final memos = obx.QueryRelationToMany<Project, RowMemo>(
    _entities[1].relations[0],
  );

  /// see [Project.secondaryCounters]
  static final secondaryCounters = obx.QueryRelationToMany<Project, Counter>(
    _entities[1].relations[1],
  );
}

/// [RowMemo] entity fields to define ObjectBox queries.
class RowMemo_ {
  /// See [RowMemo.id].
  static final id = obx.QueryIntegerProperty<RowMemo>(
    _entities[2].properties[0],
  );

  /// See [RowMemo.rowNumber].
  static final rowNumber = obx.QueryIntegerProperty<RowMemo>(
    _entities[2].properties[1],
  );

  /// See [RowMemo.content].
  static final content = obx.QueryStringProperty<RowMemo>(
    _entities[2].properties[2],
  );

  /// See [RowMemo.notified].
  static final notified = obx.QueryBooleanProperty<RowMemo>(
    _entities[2].properties[3],
  );
}
